name = "drive-api"
main = "src/index.ts"
compatibility_date = "2026-06-06"
compatibility_flags = ["nodejs_compat"]

[vars]
BETTER_AUTH_URL = ""

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "rate-limit-kv"

[[kv_namespaces]]
binding = "AUTH_KV"
id = "auth-kv"

[[r2_buckets]]
binding = "R2"
bucket_name = "drive-files"
